default_stages: [commit]

repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
      -   id: check-merge-conflict
      -   id: debug-statements

  - repo: local

    hooks:

      -   id: black
          name: black
          entry: black
          language: python
          types: [python]
          args: [
            '--line-length=120',
            '--target-version=py311',
            '--include=\\.pyi?$'
          ]

      -   id: flake8
          name: flake8
          entry: flake8
          language: python
          types: [ python ]
          args:
            - '--config=setup.cfg'
          additional_dependencies:
            - pep8-naming
            - flake8-broken-line
            - flake8-return
            - flake8-isort
            - flake8-docstrings

      -   id: isort
          name: isort
          entry: isort
          language: python
          types: [python]

      -   id: autoflake
          name: autoflake
          entry: autoflake
          language: python
          types: [python]
          args: [
            '--in-place',
            '--remove-all-unused-imports',
            '--remove-duplicate-keys',
            '--exclude=apps.py',
            '--quiet'
          ]
